<?php
	/**
	 * head.inc
	 * Contains the HTML Header for THINKer
	 *
	 * @author Cory Gehr
	 */

?>
	<title>Start | THINKer</title>
	<link rel='stylesheet' href='View/html/css/screen.css' type='text/css' media='screen'>
	<link href='View/html/css/jquery/jquery-ui-1.10.4.custom.min.css' rel='stylesheet'>
	<meta http-equiv='Content-Type' content='text/html;charset=utf-8'>
	<!-- jQuery 2.1.0 and components -->
	<script type='text/javascript' src='View/html/js/jquery-2.1.0.min.js'></script>
	<script type='text/javascript' src='View/html/js/jquery-ui-1.10.4.custom.min.js'></script>
	<script type='text/javascript' src='View/html/js/jquery.validate-1.11.1.min.js'></script>
	<script type='text/javascript' src='View/html/js/jquery.validate-additional-methods.min.js'></script>
	<script type='text/javascript' src='View/html/js/jquery.tablesorter-2.0.5.min.js'></script>
	<script type='text/javascript' src='View/html/js/jquery.tablesorter.pager.js'></script>