<?php
	/**
	 * head.inc
	 * Contains the HTML Header for THINKer
	 *
	 * @author Cory Gehr
	 */

?>
	<title>THINKer</title>
	<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
	<!-- jQuery UI CSS -->
	<link href="View/html/css/cupertino/jquery-ui-1.10.4.custom.min.css" rel="stylesheet" type="text/css" />
	<!-- THINKer CSS -->
	<link href="View/html/css/screen.css" rel="stylesheet" type="text/css" media="screen" />
	<link href="View/html/css/print.css" ref="stylesheet" type="text/css" media="print" />
	<!-- jQuery -->
	<script src="View/html/js/jquery-2.1.0.min.js"></script>
	<!-- jQuery Validate -->
	<script src="View/html/js/jquery.validate.min.js"></script>
	<script src="View/html/js/additional-methods.min.js"></script>